/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedInstructorDashboardRouteImport } from './routes/_authenticated/instructor.dashboard'
import { Route as AuthenticatedStudentCertificatesRouteImport } from './routes/_authenticated/student.certificates'
import { Route as AuthenticatedStudentDashboardRouteImport } from './routes/_authenticated/student.dashboard'
import { Route as AuthenticatedStudentProfileRouteImport } from './routes/_authenticated/student.profile'
import { Route as AuthenticatedStudentCoursesIndexRouteImport } from './routes/_authenticated/student.courses.index'
import { Route as AuthenticatedStudentCoursesCourseIdIndexRouteImport } from './routes/_authenticated/student.courses.$courseId.index'
import { Route as AuthenticatedStudentCoursesCourseIdLessonLessonIdRouteImport } from './routes/_authenticated/student.courses.$courseId.lesson.$lessonId'
import { Route as AuthenticatedStudentCoursesCourseIdQuizQuizIdRouteImport } from './routes/_authenticated/student.courses.$courseId.quiz.$quizId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstructorDashboardRoute =
  AuthenticatedInstructorDashboardRouteImport.update({
    id: '/instructor/dashboard',
    path: '/instructor/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentCertificatesRoute =
  AuthenticatedStudentCertificatesRouteImport.update({
    id: '/student/certificates',
    path: '/student/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentDashboardRoute =
  AuthenticatedStudentDashboardRouteImport.update({
    id: '/student/dashboard',
    path: '/student/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentProfileRoute =
  AuthenticatedStudentProfileRouteImport.update({
    id: '/student/profile',
    path: '/student/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentCoursesIndexRoute =
  AuthenticatedStudentCoursesIndexRouteImport.update({
    id: '/student/courses/',
    path: '/student/courses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentCoursesCourseIdIndexRoute =
  AuthenticatedStudentCoursesCourseIdIndexRouteImport.update({
    id: '/student/courses/$courseId/',
    path: '/student/courses/$courseId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentCoursesCourseIdLessonLessonIdRoute =
  AuthenticatedStudentCoursesCourseIdLessonLessonIdRouteImport.update({
    id: '/student/courses/$courseId/lesson/$lessonId',
    path: '/student/courses/$courseId/lesson/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentCoursesCourseIdQuizQuizIdRoute =
  AuthenticatedStudentCoursesCourseIdQuizQuizIdRouteImport.update({
    id: '/student/courses/$courseId/quiz/$quizId',
    path: '/student/courses/$courseId/quiz/$quizId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/instructor/dashboard': typeof AuthenticatedInstructorDashboardRoute
  '/student/certificates': typeof AuthenticatedStudentCertificatesRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/student/courses/': typeof AuthenticatedStudentCoursesIndexRoute
  '/student/courses/$courseId/': typeof AuthenticatedStudentCoursesCourseIdIndexRoute
  '/student/courses/$courseId/lesson/$lessonId': typeof AuthenticatedStudentCoursesCourseIdLessonLessonIdRoute
  '/student/courses/$courseId/quiz/$quizId': typeof AuthenticatedStudentCoursesCourseIdQuizQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/courses': typeof CoursesIndexRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/instructor/dashboard': typeof AuthenticatedInstructorDashboardRoute
  '/student/certificates': typeof AuthenticatedStudentCertificatesRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/student/courses': typeof AuthenticatedStudentCoursesIndexRoute
  '/student/courses/$courseId': typeof AuthenticatedStudentCoursesCourseIdIndexRoute
  '/student/courses/$courseId/lesson/$lessonId': typeof AuthenticatedStudentCoursesCourseIdLessonLessonIdRoute
  '/student/courses/$courseId/quiz/$quizId': typeof AuthenticatedStudentCoursesCourseIdQuizQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/instructor/dashboard': typeof AuthenticatedInstructorDashboardRoute
  '/_authenticated/student/certificates': typeof AuthenticatedStudentCertificatesRoute
  '/_authenticated/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/_authenticated/student/profile': typeof AuthenticatedStudentProfileRoute
  '/_authenticated/student/courses/': typeof AuthenticatedStudentCoursesIndexRoute
  '/_authenticated/student/courses/$courseId/': typeof AuthenticatedStudentCoursesCourseIdIndexRoute
  '/_authenticated/student/courses/$courseId/lesson/$lessonId': typeof AuthenticatedStudentCoursesCourseIdLessonLessonIdRoute
  '/_authenticated/student/courses/$courseId/quiz/$quizId': typeof AuthenticatedStudentCoursesCourseIdQuizQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/login'
    | '/register'
    | '/courses/$courseId'
    | '/courses/'
    | '/admin/dashboard'
    | '/instructor/dashboard'
    | '/student/certificates'
    | '/student/dashboard'
    | '/student/profile'
    | '/student/courses/'
    | '/student/courses/$courseId/'
    | '/student/courses/$courseId/lesson/$lessonId'
    | '/student/courses/$courseId/quiz/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/courses/$courseId'
    | '/courses'
    | '/admin/dashboard'
    | '/instructor/dashboard'
    | '/student/certificates'
    | '/student/dashboard'
    | '/student/profile'
    | '/student/courses'
    | '/student/courses/$courseId'
    | '/student/courses/$courseId/lesson/$lessonId'
    | '/student/courses/$courseId/quiz/$quizId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/courses'
    | '/login'
    | '/register'
    | '/courses/$courseId'
    | '/courses/'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/instructor/dashboard'
    | '/_authenticated/student/certificates'
    | '/_authenticated/student/dashboard'
    | '/_authenticated/student/profile'
    | '/_authenticated/student/courses/'
    | '/_authenticated/student/courses/$courseId/'
    | '/_authenticated/student/courses/$courseId/lesson/$lessonId'
    | '/_authenticated/student/courses/$courseId/quiz/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CoursesRoute: typeof CoursesRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instructor/dashboard': {
      id: '/_authenticated/instructor/dashboard'
      path: '/instructor/dashboard'
      fullPath: '/instructor/dashboard'
      preLoaderRoute: typeof AuthenticatedInstructorDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/certificates': {
      id: '/_authenticated/student/certificates'
      path: '/student/certificates'
      fullPath: '/student/certificates'
      preLoaderRoute: typeof AuthenticatedStudentCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/dashboard': {
      id: '/_authenticated/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof AuthenticatedStudentDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/profile': {
      id: '/_authenticated/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof AuthenticatedStudentProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/courses/': {
      id: '/_authenticated/student/courses/'
      path: '/student/courses'
      fullPath: '/student/courses/'
      preLoaderRoute: typeof AuthenticatedStudentCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/courses/$courseId/': {
      id: '/_authenticated/student/courses/$courseId/'
      path: '/student/courses/$courseId'
      fullPath: '/student/courses/$courseId/'
      preLoaderRoute: typeof AuthenticatedStudentCoursesCourseIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/courses/$courseId/lesson/$lessonId': {
      id: '/_authenticated/student/courses/$courseId/lesson/$lessonId'
      path: '/student/courses/$courseId/lesson/$lessonId'
      fullPath: '/student/courses/$courseId/lesson/$lessonId'
      preLoaderRoute: typeof AuthenticatedStudentCoursesCourseIdLessonLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/courses/$courseId/quiz/$quizId': {
      id: '/_authenticated/student/courses/$courseId/quiz/$quizId'
      path: '/student/courses/$courseId/quiz/$quizId'
      fullPath: '/student/courses/$courseId/quiz/$quizId'
      preLoaderRoute: typeof AuthenticatedStudentCoursesCourseIdQuizQuizIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedInstructorDashboardRoute: typeof AuthenticatedInstructorDashboardRoute
  AuthenticatedStudentCertificatesRoute: typeof AuthenticatedStudentCertificatesRoute
  AuthenticatedStudentDashboardRoute: typeof AuthenticatedStudentDashboardRoute
  AuthenticatedStudentProfileRoute: typeof AuthenticatedStudentProfileRoute
  AuthenticatedStudentCoursesIndexRoute: typeof AuthenticatedStudentCoursesIndexRoute
  AuthenticatedStudentCoursesCourseIdIndexRoute: typeof AuthenticatedStudentCoursesCourseIdIndexRoute
  AuthenticatedStudentCoursesCourseIdLessonLessonIdRoute: typeof AuthenticatedStudentCoursesCourseIdLessonLessonIdRoute
  AuthenticatedStudentCoursesCourseIdQuizQuizIdRoute: typeof AuthenticatedStudentCoursesCourseIdQuizQuizIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedInstructorDashboardRoute: AuthenticatedInstructorDashboardRoute,
  AuthenticatedStudentCertificatesRoute: AuthenticatedStudentCertificatesRoute,
  AuthenticatedStudentDashboardRoute: AuthenticatedStudentDashboardRoute,
  AuthenticatedStudentProfileRoute: AuthenticatedStudentProfileRoute,
  AuthenticatedStudentCoursesIndexRoute: AuthenticatedStudentCoursesIndexRoute,
  AuthenticatedStudentCoursesCourseIdIndexRoute:
    AuthenticatedStudentCoursesCourseIdIndexRoute,
  AuthenticatedStudentCoursesCourseIdLessonLessonIdRoute:
    AuthenticatedStudentCoursesCourseIdLessonLessonIdRoute,
  AuthenticatedStudentCoursesCourseIdQuizQuizIdRoute:
    AuthenticatedStudentCoursesCourseIdQuizQuizIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CoursesRoute: CoursesRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
